### ISSUE TITLE
QP de/coding

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#124]
Implement quoted-printable en/decoding similarly to String/Hex. Without active selection operate on whole document. 

Place the commands below `Hex to String` and assign hotkeys Alt+Shift+Q (qp -> str) and Ctrl+Alt+Shift+Q (str -> qp).

QP encoding is described in http://www.faqs.org/rfcs/rfc2045 (section 6.7). It is simple and very similar to already implemented URL encoding. QP commonly appears in MIME messages and in vCard files.

Both QP and Base64 de/coding are implemented in Notepad++ `MIME Tools` plugin.

**Comment by cshnik** [comment]
Required changes added.

**Comment by ProgerXP** [comment]
I'd like to know if this is the intended behaviour and not some buffer overrun.

Have this document:
```
8F=D0=
```

Do QP Decode. Result:
```
[8FР=]NUL=
```

1. Why NUL?
2. Why only part of the result selected?

If this is because input is not a valid QP source then it should either stop at first invalid character or try to decode as much as possible, without corrupting the buffer.

**Comment by cshnik** [comment]
There was a bug in the QP decoding proc which caused decoding of incorrect data.
1. Decoding of 8F=D0= gives [8FÐ]= when working with ANSI document encoding.
2. Decoded text is partially selected due the next reasons:
  a. There was an error when decoding last characters.
  b. To display the actual transformed/decoded text part. Complete text is selected in case of no errors.
  c. To help user to revert the change, user can use encode procedure on the selected text block and completely rollback the change (Undo is not so convenient here because it always looses selection).
  d. The same common logic is shared with other recoding procedures, e.g. Base64.
