### ISSUE TITLE
SelectionType = 0

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#146]
From the code it seems that when a ...SelectionType setting is set to 0 then all indication should be disabled. However, text is still underlined by a certain color. Try putting this into the INI:
```
PageSelectionType=0
```

And use this document:
```
aa aa aa
```

Why `aa`s are underlined? Is it intentional?

**Comment by cshnik** [comment]
Indicator style 0 is INDIC_PLAIN: Underlined with a single, straight line.
Please use INDIC_HIDDEN (5) to hide/disable visual representation for indicator.
[Scintilla's indicator styles](http://www.scintilla.org/ScintillaDoc.html#SCI_INDICSETSTYLE)

Symbol | Value | Visual effect
-- | -- | --
INDIC_PLAIN | 0 | Underlined with a single, straight line.
INDIC_SQUIGGLE | 1 | A squiggly underline. Requires 3 pixels of descender space.
INDIC_TT | 2 | A line of small T shapes.
INDIC_DIAGONAL | 3 | Diagonal hatching.
INDIC_STRIKE | 4 | Strike out.
INDIC_HIDDEN | 5 | An indicator with no visual effect.
INDIC_BOX | 6 | A rectangle around the text.
INDIC_ROUNDBOX | 7 | A rectangle with rounded corners around the text using translucent drawing with the interior usually more transparent than the border. You can useSCI_INDICSETALPHA and SCI_INDICSETOUTLINEALPHA to control the alpha transparency values. The default alpha values are 30 for fill colour and 50 for outline colour.
INDIC_STRAIGHTBOX | 8 | A rectangle around the text using translucent drawing with the interior usually more transparent than the border. You can use SCI_INDICSETALPHA andSCI_INDICSETOUTLINEALPHA to control the alpha transparency values. The default alpha values are 30 for fill colour and 50 for outline colour. This indicator does not colour the top pixel of the line so that indicators on contiguous lines are visually distinct and disconnected.
INDIC_FULLBOX | 16 | A rectangle around the text using translucent drawing similar to INDIC_STRAIGHTBOX but covering the entire character area.
INDIC_DASH | 9 | A dashed underline.
INDIC_DOTS | 10 | A dotted underline.
INDIC_SQUIGGLELOW | 11 | Similar to INDIC_SQUIGGLE but only using 2 vertical pixels so will fit under small fonts.
INDIC_DOTBOX | 12 | A dotted rectangle around the text using translucent drawing. Translucency alternates between the alpha and outline alpha settings with the top-left pixel using the alpha setting. SCI_INDICSETALPHA and SCI_INDICSETOUTLINEALPHA control the alpha transparency values. The default values are 30 for alpha and 50 for outline alpha. To avoid excessive memory allocation the maximum width of a dotted box is 4000 pixels.
INDIC_SQUIGGLEPIXMAP | 13 | A version of INDIC_SQUIGGLE that draws using a pixmap instead of as a series of line segments for performance. Measured to be between 3 and 6 times faster than INDIC_SQUIGGLE on GTK+. Appearance will not be as good as INDIC_SQUIGGLE on OS X in HiDPI mode.
INDIC_COMPOSITIONTHICK | 14 | A 2-pixel thick underline located at the bottom of the line to try to avoid touching the character base. Each side is inset 1 pixel so that different indicators in this style covering a range appear isolated. This is similar to an appearance used for the target in Asian language input composition.
INDIC_COMPOSITIONTHIN | 15 | A 1-pixel thick underline located just before the bottom of the line. Each side is inset 1 pixel so that different indicators in this style covering a range appear isolated. This is similar to an appearance used for non-target ranges in Asian language input composition.
INDIC_TEXTFORE | 17 | Change the colour of the text to the indicator's fore colour.
INDIC_POINT | 18 | Draw a triangle below the start of the indicator range.
INDIC_POINTCHARACTER | 19 | Draw a triangle below the centre of the first character of the indicator range.
