### ISSUE TITLE
Regexp replace \N freeze

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#163]
Any document, do Replace from `\N` to `123` - the program will become unresponsive.

**Comment by cshnik** [comment]
Fixed.

**Comment by ProgerXP** [comment]
What was the cause?

**Comment by cshnik** [comment]
> What was the cause? What's special about `\N`?

There was an unhandled exception thrown from regexp internals when trying to compile/use incorrectly formatted value. `\N` is not a valid special character.

**Comment by ProgerXP** [comment]
Was it necessary to change Scintilla internals? Notepad++ doesn't have such a problem.

**Comment by cshnik** [comment]
> Was it necessary to change Scintilla internals?

``BoostRegExSearch.cxx`` is not a part of original Scintilla's code base. This is an auxiliary class for Scintilla which implements custom regex capabilities. We use adopted boost regex implementation which originally came from Notepad++. Since boost regex is written in C++ our code should rely on exception model which is used to notify about incorrect values.

**Comment by ProgerXP** [comment]
> `boost::regex_constants::ECMAScript`

What does this flag do?

> 
```
+		try
+		{
+			found = boost::regex_search(itStart, itEnd, _match, _regex, search._boostRegexFlags);
+		}
+		catch (...)
+		{
+			found = false;
+		} 
```

Cannot you catch the exception in our code rather than silencing it in BoostRegExSearch?
