### ISSUE TITLE
Replace text always selected even without focus

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#172]
Last build has a strange effect in Win7 and Win10 (not XP): document = `a`, Replace from `a` to `a`, open Replace dialog again with Ctrl+H - Search String is focused and selected (correct) but Replace With string is also selected - even though it's not focused. This was introduced some time in last several months.

![screen](https://user-images.githubusercontent.com/1643195/40281181-7aab5e7e-5c4d-11e8-93c9-1147262950c8.png)

**Comment by cshnik** [comment]
The actual reason is: WM_SETFONT message sent from DPI subroutine (implemented in #154) does not properly handled by the replace text combo (standard OS message handler is used) when it has initialized text/selection (the issue occured within dialog initialization proc) and caused combo to always display contents as selected (even after complete redrawing).
The fix: DPI initialization call moved to the very beginning of the dialog initialization proc before populating of the replace text value.
