### ISSUE TITLE
Attribution menu command

### ISSUE THREAD

**Issue by csware** [ProgerXP/Notepad2e#181]
You use base64.c which is 3-clause BSD licensed. Here you are required to proper attribute credits to the author in source AND binary redistribution. In source you have the license file, but attribution is missing the in binary distribution.

**Comment by ProgerXP** [comment]
![attrib](https://user-images.githubusercontent.com/1643195/44080175-edf8412c-9fb3-11e8-8779-f90918039a84.png)

**Comment by csware** [comment]
As you can see there is no attribution for the base64 authors.

**Comment by ProgerXP** [comment]
@csware 
My bad, I didn't notice you were talking about base64.c. Good catch.

---

@cshnik After finishing more important tasks I'll assign you to this one.

1. Add new menu command below `? > About...` named `3rd Party Code...` (no hotkey).
2. Let it display a modal dialog with an icon, a readonly textarea and OK button (layout similar to About except that labels are replaced by the textarea).
3. Use this text (as is):

```
== base64 ==
http://web.mit.edu/freebsd/head/contrib/wpa/src/utils/

<copy text of src/Extension/base64-license.txt below>
Copyright (c) ...
...
...POSSIBILITY OF SUCH DAMAGE.

== tinyexpr ==
https://codeplea.com/tinyexpr

<copy text of src/Extension/tinyexpr/LICENSE.md below>
```

4. Move base64* files into their own folder (like with tinyexpr) since it's not our own code.

By the way, where did you get the license file? I don't see one at http://web.mit.edu/freebsd/head/contrib/wpa/src/utils/

**Comment by cshnik** [comment]
> By the way, where did you get the license file? I don't see one at http://web.mit.edu/freebsd/head/contrib/wpa/src/utils/

Base64 license text was composed from general copying notice and license text for wpa_supplicant and hostapd: http://web.mit.edu/freebsd/head/contrib/wpa/

**Comment by cshnik** [comment]
?> "3rd Party Code..." dialog implemented.

**Comment by cshnik** [comment]
> What's that?

Rich text file which is displayed in the read only edit placed on newly implemented dialog (includes all required data related to 3rd parties: links, text).

**Comment by ProgerXP** [comment]
But why is it using an absolute path on your system?

**Comment by cshnik** [comment]
> But why is it using an absolute path on your system?

Fixed.

**Comment by csware** [comment]
@cshnik @ProgerXP 
I looked in the history and most of the commit messages are not helpful. For this issue, there are 3 commits which all have a very similar subject.

Ever thought of using branches for fixing issues which require several commits and then merging them with non-fast-forward or squashing commits which belong togehter?

**Comment by ProgerXP** [comment]
> Ever thought of using branches for fixing issues which require several commits and then merging them with non-fast-forward or squashing commits which belong togehter?

Yes, but given a team of basically 1 person and small and frequent tasks it complicates the development somewhat since you can't commit to master or dev directly and have to additionally merge/squash them.

Personally I find current verbosity of commit messages adequate since most discussion happens in the issues anyway, and every commit includes a reference to it.

**Comment by cshnik** [comment]
"3rd party code" dialog will be ugly and unhandy when using basic text input due to the next reasons:
1. Plain text input does not support neither fonts or text decorations/colors. The content will merge and it would be difficult for reading.
2. Plain text input does not support correct display and navigation for links. User will have to manually copy-paste the url into his browser to navigate to web-resource. Such behavior is not user-friendly and violates the currently used UI scheme: links are widely used in the About, Find, Replace, Modify Lines dialogs.

Are there any other problems with current implementation?
Please confirm if you still insist on a rollback for recent changes.

**Comment by ProgerXP** [comment]
Given that most changes in the last commit are related to subclassing which is used in other places, not only this new dialog, we can leave it as is.
