### ISSUE TITLE
Selection highlighting (Mark occurrences)

### ISSUE THREAD

**Issue by Progress1** [ProgerXP/Notepad2e#211]
What about **Selection highlighting**. It marks what user select. With combination of these settings we can cover all cases. It's different like current **Current Word Highlighting**

Inspire here:
![image](https://user-images.githubusercontent.com/10151485/52631055-173c4300-2ebe-11e9-85e4-b870389619f7.png)

It's already implemented in https://xhmikosr.github.io/notepad2-mod/

**Comment by ProgerXP** [comment]
> What about Selection highlighting. It marks what user select. 

You can achieve this by using Edit Selection (https://github.com/ProgerXP/Notepad2e#new-edit-selection). Select what you need, press Ctrl+Tab or Ctrl+Backtick - it will highlight the occurrences, then press Escape to leave this mode and remove highlighting.

As for "Off/Blue/Match Case/etc" in the menu - I have no plans of adding these to the Notepad 2e's menu because it's already big and because changing these settings on the fly is not very useful (they're normally set once in the INI and forgotten about). But you can still toggle word highlighting on/off via the menu.

**Comment by Progress1** [comment]
But this works only if **Highlight Current Word** is enabled. I have this option OFF (i use only **Highlight Current Line**) It should works no matter what highlighting is on or off. Also when you scroll document with scrollbar it disappear (it's bug) because when you scroll with mouse it stay highlighted.
This is very powerful functionality! I use it every day. Maybe colors can be used from Highlight Current Word states (just use fill, no rectangle for coloring). Case Sensitivity and Whole word option in this case is also important! These settings needs to be changed on the fly (no .ini play, fast switching)

tested on Notepad2e-R67-4744880-x64

**Comment by ProgerXP** [comment]
> But this works only if Highlight Current Word is enabled. 

Yes, that's how it's implemented, for simplicity, because both features (edit and highlight word) are using the same underlying mechanism. 

You can enable Highlight Current Word without any visual indication (as if it was disabled) by setting MaxSearchDistance to 0 (although I haven't tried this) or setting all highlight colors to transparent/alpha to 0/type to 5 (see the readme).

> Also when you scroll document with scrollbar - it disappear (it's bug) 

It's actually intentional, because Edit Word works within the same page (text visible on one screen). Otherwise you'll be editing words outside of what you see, which may lead to unexpected results.

> Maybe colors can be used from Highlight Current Word states (just use fill, no rectangle for coloring). 

They can be, see https://github.com/ProgerXP/Notepad2e#current-word-highlighting

> Case Sensitivity and Whole word option in this case is also important! 

Currently Edit Word works this way: if you have no selection, it uses case sensitive = off, whole word = on. If you have selection, it's case sensitive = on, whole word = off.

I understand you might have special needs but frankly I see limited use of this and personally I'm very happy with Highlight Word and Edit Word at their current shape, which is both simple and powerful. I don't want to change them.

**Comment by cup** [comment]
https://github.com/ProgerXP/Notepad2e/issues/211
https://github.com/ProgerXP/Notepad2e/issues/246
https://github.com/ProgerXP/Notepad2e/issues/255

**Comment by cup** [comment]
@ProgerXP I have the same concern here.

If you turn off "Highlight Current Word", then you also lose the
"Edit Selection" (`Ctrl + Tab`) option.

Personally I dont need to Edit any Selections, but the key is useful also for
*viewing selections*. And its a problem because I dont want to see the current
word highlighted, but I do want to see selection occurences highlighted.

If you can implement this I can donate $100

**Comment by ProgerXP** [comment]
> And its a problem because I dont want to see the current word highlighted, but I do want to see selection occurences highlighted.

Why don't you customize highlighting styles to make them transparent of all except `Edit` mode? Visually this will look like Highlight Current Word is disabled while leaving Edit Selection working.

> If you can implement this I can donate $100

If you want any help then please do not delete any issues or comments. It's creating a real mess.

**Comment by cup** [comment]
> Why don't you customize highlighting styles to make them transparent of all except Edit mode? Visually this will look like Highlight Current Word is disabled while leaving Edit Selection working.

I can do this, but doesnt that mean still incurring a performance hit as the feature is not actually disabled but hidden?

> If you want any help then please do not delete any issues or comments. It's creating a real mess.

I apologize for this, GitHub admins flagged my account recently so every issue I ever posted (hundreds) has been hidden from everyone but myself. Thanks for understanding.

**Comment by ProgerXP** [comment]
> I can do this, but doesnt that mean still incurring a performance hit as the feature is not actually disabled but hidden?

Yes, it will have an impact on performance but will you feel it? In my experience it starts micro-lagging on very large files only, and then we have a setting to control how large file portion is scanned for highlighting so adjusting it may minimize this impact. So try doing this and see if it works for you.

Of course ideally you could be able to turn off these two features separately but I feel we can't implement it now because word highlighting was among the first things we made in 2013 and I think Edit Word's internal operation depends on highlighting being enabled beforehand so separate settings might require a good deal of refactoring.

> I apologize for this, GitHub admins flagged my account recently so every issue I ever posted (hundreds) has been hidden from everyone but myself. Thanks for understanding.

Okay, I thought you made it on purpose. It kind of messed up our workflow.

**Comment by cup** [comment]
I am increasing bounty to $200, thank you.

**Comment by ProgerXP** [comment]
I will reconsider this feature after we release the new version in March.

**Comment by cup** [comment]
I am increasing bounty to $800, thank you.

**Comment by ProgerXP** [comment]
I don't know what that @cup or whatever is doing but he has deleted his posts AGAIN. THIRD TIME NOW!

We are not going to work on this feature anymore. Let's wish him rays of love.

**Comment by ProgerXP** [comment]
@cup

I have the same concern here.

If you turn off "Highlight Current Word", then you also lose the "Edit Selection" (`Ctrl + Tab`) option.

Personally I don't need to Edit any Selections, but the key is useful also for *viewing selections*. And its a problem because I don't want to see the current word highlighted, but I do want to see selection occurences highlighted.

---

@cup

> Why don't you customize highlighting styles to make them transparent of all except Edit mode? Visually this will look like Highlight Current Word is disabled while leaving Edit Selection working.

I can do this, but doesn't that mean still incurring a performance hit as the feature is not actually disabled but hidden?

**Comment by muv1** [comment]
@ProgerXP yes my account (@cup) was flagged again. I apologize, but I cant
control what GitHub admins do. My account is getting flagged repeatedly without
explanation or response from admins.

I dont see why this issue should be closed though, as @cup didnt even open it.
Also issues should be resolve based on merit, not based on who opened the issue.
At any rate, if you were to reconsider donation $800 will be made upon
completion. Thanks for understanding.
