### ISSUE TITLE
ICU build, regexp and UTF-8 BOM 

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#231]
Previously we have added a warning that in ICU builds regexps only work on Unicode buffers. Does the buffer have to be exactly UTF-8 or it  can be UCS, with BOM, etc. but still Unicode?

**Comment by cshnik** [comment]
File's content does not directly used when executing ICU regex due to the following reasons:
1. Scintilla internally uses utf8 encoding (convert data on file load: unicode -> utf8).
2. ICU regex operates with utf32 strings. This requires additional data conversion (utf8 -> utf32).

All types of unicode files should be properly supported in the ICU build:
1. utf8/utf16LE/RE
2. utf8/utf16LE/RE + BOM

**Comment by ProgerXP** [comment]
Due to some recent change (cd16d71 or 9156be3), a test started to fail:

```
Assert failed. Decoding, Unicode encoding,  source: TestFile1__src_UTF8.txt. 
test\extension\textencodingtests.cpp, DoRecodingTest	line 70
	at DoRecodingTest() in test\extension\textencodingtests.cpp:line 73
```

**Comment by ProgerXP** [comment]
> All types of unicode files should be properly supported in the ICU build:

But it still warns on UTF-8 Signature.

**Comment by cshnik** [comment]
> But it still warns on UTF-8 Signature.

Fixed: removed useless prompt for UTF-8 Signature encoding when running regex in the ICU build.
