### ISSUE TITLE
Go To UI changes

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#263]
- For some reason Go To's inputs are taller than standard inputs (in Find/Replace). Make them the same. 
- Reduce empty space between the text label and the input (see the screenshot for guidance).

![GoToUI](https://user-images.githubusercontent.com/1643195/74438853-16950e80-4e7c-11ea-84f6-56a5ced6ae7f.png)

**Comment by ProgerXP** [comment]
#259 improved the layout but Go To's inputs are still too tall and also not aligned in the same way as in Find, i.e. Line and Column inputs' Y coord should be the same as Search String in Find. See the comparison - Go To's inputs must be moved up by 4 pixels and their height must be reduced by 3 pixels.

![Alignment10](https://user-images.githubusercontent.com/1643195/74533038-b072bf00-4f41-11ea-9426-7fd697cc6c70.png)

**Comment by cshnik** [comment]
Fixed edit position (**done**) and size (**not done**).
Please consider the following:
1. Find/Replace dialogs uses ComboBox controls
2. Goto dialog uses Edit control
3. [How To: Layout Controls (C++)](https://docs.microsoft.com/en-us/cpp/windows/arrangement-of-controls-on-dialog-boxes?view=vs-2019)
> The tick marks in the rulers that determine the spacing of guides and controls are defined by dialog units (DLUs). A DLU is based on the size of the dialog box font, normally 8-point MS Shell Dlg. A horizontal DLU is the average width of the dialog box font divided by four. A vertical DLU is the average height of the font divided by 8.
4. Microsoft UX guide (http://www.glyfx.com/useruploads/files/UXGuide.pdf) stated edit and combobox controls should have the same sizes (14DLUs):
![image](https://user-images.githubusercontent.com/8019354/74554889-1afd1c80-4f8d-11ea-948b-44e44a59642b.png)
![image](https://user-images.githubusercontent.com/8019354/74554926-3536fa80-4f8d-11ea-9f88-63405a57a055.png)
But this rule is not properly supported even by Windows OS.
5. Manual test with creation of new dialog with default Edit and ComboBox controls revealed these have different height (edit has 14 DLUs height,  while ComboBox has no option for its height, only height for expanded menu). The actual difference in default DPI mode is 2px.
6. Additional research with Spy++ for standard Windows OS dialogs (which are DPI-unaware) gives the same result: Edit and ComboBox control have always different height (but the difference is visually much less), e.g user picker tool:
![image](https://user-images.githubusercontent.com/8019354/74555472-5cda9280-4f8e-11ea-8701-d80321d87cdf.png)
7. Using of DPI-aware mode makes the difference more perceptible due to the scaling of the actual window height.

At this point I see no way to make Edit and ComboBox in specified dialogs always has exactly the same heights.

**Comment by ProgerXP** [comment]
Nice research. I didn't know of these limitations. We will keep the current version.
