### ISSUE TITLE
Find/Replace - handle Ctrl+Enter

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#273]
When Find or Replace is submitted by Enter while Ctrl is held down, perform the search from the beginning of the document. This could be done manually like this:

1. Put a caret at the beginning (Ctrl+Home)
2. Invoke Find or Replace
3. Submit it with Enter

However, unlike these manual steps Ctrl+Enter does not change the caret or scroll position if there is no match - they remain as they were before dialog submission.

**Comment by cshnik** [comment]
Done.

**Comment by ProgerXP** [comment]
> `if (!EditFindNext(lpefr->hwnd, lpefr, LOWORD(wParam) == IDACC_SELTONEXT))`

This works just as expected but what does IDACC_SELTONEXT mean here? If it's supposed to enable Ctrl+F2 by analogy with Ctrl+Enter (select to first match) then it doesn't work.

**Comment by cshnik** [comment]
> This works just as expected but what does IDACC_SELTONEXT mean here?

Please consider the following:
1. This was a copy-paste of original code line. Initial thought was to provide original call AS IS.
2. The  actual value of ``LOWORD(wParam) == IDACC_SELTONEXT`` is always ``FALSE`` here since ``Ctrl+F2`` will never be treated as "Selection to next" accelerator (IDACC_SELTONEXT), which is defined as ``F2``.
3. We can change this condition value to ``FALSE`` explicitly if it makes sense to document current behavior. Please confirm if we should do this.

**Comment by ProgerXP** [comment]
> Please confirm if we should do this.

Yes. Moreover, select-to can't really work because we are resetting the caret position. So this makes it confusing - should be made `FALSE`.

**Comment by cshnik** [comment]
Fixed.
