### ISSUE TITLE
Main menu: use radio buttons instead of checkboxes for choices

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#300]
Currently some menu groups are using check marks even if they are mutually exclusive. Compare: 

- Settings > Esc Key Function - circles
- View > Highlight Current Selection - check marks

Review all command groups and replace check marks with circles where applicable (as with Highlight Current Selection).

**Comment by ProgerXP** [comment]
> assert(FALSE);

It's not a very good idea to use assertions since they can be disabled. Let's use `abort();` instead.

**Comment by cshnik** [comment]
Please consider the following:
1. These asserts were added for debugging needs in runtime, application abort in runtime was not expected (and is extremely unpleasant for user) even if required code was missing.
2. Since these asserts are runtime statements we have nothing to do to abort compilation.

Please confirm if we should completely remove it from the code.

**Comment by ProgerXP** [comment]
Are we using NDEBUG in the release version? Or are these asserts a no-op?

**Comment by cshnik** [comment]
> Are we using NDEBUG in the release version? Or are these asserts a no-op?

NDEBUG is set for Release configurations which makes asserts() act as no-op. Thus, these asserts() are functional only in the Debug build code.
