### ISSUE TITLE
Disable ScrollYCaretPolicy in page-wise Edit Mode

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#337]
When inside Edit Mode that is affecting current page (screen), do not scroll the screen according to `ScrollYCaretPolicy` (#41) because it causes edit regions to shift and some of them become hidden.

**Comment by cshnik** [comment]
Done.

**Comment by ProgerXP** [comment]
> n2e_SelectionEditIsVisibleOnScreen()

What is this check for?

**Comment by cshnik** [comment]
> > n2e_SelectionEditIsVisibleOnScreen()
> 
> What is this check for?

``n2e_SelectionEditIsVisibleOnScreen()`` will check if there are any visible entries (related to Edit mode) on current page.
1. If there are visible entries on screen - skip scrolling as requested in this issue.
2. If there are no visible entries - force document scrolling (as previously implemented) to show user his active selection.

Behavior in point 2 is useful in the following scenario:
1. Start Edit mode
2. Use mouse scrolling to scroll document until active entry get hidden and no other entries are visible (Edit mode is still active)
3. Continue text input in Edit mode
Expected behavior: user should see the part of the document he is working at.

**Comment by cshnik** [comment]
Fixed.

**Comment by cshnik** [comment]
Disabled automatic document scrolling when working in page-wise edit mode,
