### ISSUE TITLE
Make Open dialog resizable

### ISSUE THREAD

**Issue by Anton-V-K** [ProgerXP/Notepad2e#400]
Open dialog isn't resizable, while many (all?) other file-related dialogs are.

**Comment by Anton-V-K** [comment]
The Save dialog (Ctrl+S) is resizable, while the Open dialog (Ctrl+O) is not:
![image](https://user-images.githubusercontent.com/20116984/153056591-5e3dba3a-28d5-44a3-bdc7-85189e863330.png)
There is no resizable sign in the bottom right corner (Windows 10 21H1 64-bit).
Reproducible with `Notepad2e-R213-7158575-x86`
Same issue in Windows 8.1 64-bit, Windows 7 SP1 32-bit

**Comment by ProgerXP** [comment]
> Is there a option which can tweak the open dialog?

Apparently this is caused by the dialog hook that allows opening files by prefix (#165). The hook is only added to the open file dialog so you should see that dialog using old-style controls (Places Bar instead of the directory tree on the left) while the save dialog that is not hooked is modern and has the resize grip.

Therefore it's not a bug. Either disable Notepad 2e's open by prefix or enable Windows' open by prefix (it will automatically disable Notepad 2e's, remove the hook and make the open dialog resizable).
