### ISSUE TITLE
feature_request: allow adding custom hotkeys for Scintilla commands

### ISSUE THREAD

**Issue by insomnimus** [ProgerXP/Notepad2e#420]
I've recently discovered this project and it's great.

I'm used to Notepad++ but was looking for something closer to the original Notepad.

In Notepad++ one can change hotkeys and even add new ones that trigger a Scintilla command.

Being a screen reader user (I am visually impaired) this is one of the most important features of Scintilla based editors to me
since I only use my keyboard (no mouse) and try to make the most of keyboard shortcuts.

Without looking at the code base I'd think this would be an easy enough feature to implement.
What do you think?

**Comment by ProgerXP** [comment]
> I'm not sure about gvim but vim itself is quite unusable with a screen reader, perhaps because it's a TUI program. I will have a look at gvim!

If TUI is the only issue then Gvim may work better with a screenreader since it has a proper GUI frontend (but the same Vim engine on the inside).

> I don't think I would change existing hotkeys. I was mainly thinking of associating some unbound (as far as i can tell) hotkeys to some Scintilla commands like going to the start of the line or killing the current line.

You will be hard pressed to find an editing command that doesn't have a hotkey assigned. I personally never use context or main menu of Notepad 2e though I've written literally 100,000s LOC in this editor over the years.

For instance, "going to the start of the line" = Home (or `Home, Home` if word wrapping is on), "killing the current line" = Ctrl+Shift+D (Ctrl+Shift+X/C also exist, for Cut/Copy of the current line).

> Ah actually think I might change "go to brace" to `ctrl-t` and select between braces to `ctrl-shift-t`.

Yep, this is why I said it's subjective. C+[S+]T combinations are inherited from Notepad2 where Ctrl+T opens Tab Settings and Ctrl+Shift+T converts spaces to Tabs in the selection (Ctrl+Shift+S does the reverse). For me, Ctrl+B is easier to press than Ctrl+T so I find this scheme acceptable.

> As for the custom compilation, I wouldn't want to bother you with it since I am able to compile it on my machine - however a pointer on where I should look would be perfect!

Notepad 2/2e hotkeys are defined in Notepad2.rc making them trivial to remap. For example, Ctrl+B - Find Matching Brace:

https://github.com/ProgerXP/Notepad2e/blob/7cd5885dd553f67765871bcf83f8bb7c1957aea0/src/Notepad2.rc#L454

**Comment by insomnimus** [comment]
Perfect, thank you for all your help! I wasn't aware those hotkeys existed so just remapping them is enough for me.

**Comment by insomnimus** [comment]
I've closed the issue but now that i look at the rc file I can't locate the hotkeys for "go to start of the line" and "go to end of the line"; I've ctrl-f'd for "home" and "line" to no avail.
Are they named differently?

(commit `7cd5885`, 
the most recent as of this writing.)

**Comment by ProgerXP** [comment]
> I've closed the issue but now that i look at the rc file I can't locate the hotkeys for "go to start of the line" and "go to end of the line"; I've ctrl-f'd for "home" and "line" to no avail.

These are native Scintilla hotkeys. If Notepad 2e doesn't override them, you can find them here:

https://github.com/ProgerXP/Notepad2e/blob/7cd5885dd553f67765871bcf83f8bb7c1957aea0/scintilla/src/KeyMap.cxx#L107

Look here for the description of what `SCI_...` commands do:

https://github.com/ProgerXP/Notepad2e/blob/7cd5885dd553f67765871bcf83f8bb7c1957aea0/scintilla/doc/ScintillaDoc.html#L5432-L5434

**Comment by insomnimus** [comment]
And with that all my keybinds are complete.

Thank you so much again for all the help and the great editor!
