### ISSUE TITLE
Selection start changes if replacing leading substring

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#468]
Normally, Replace retains cursor and selection positions but not when the string was found in the beginning of the selection: `[abcabc]` - Replace from `a` to `z`, get `z[bczbc]` rather than `[zbczbc]`.

**Comment by cshnik** [comment]
Created bug for Scintilla: [#2393 Incorrect selection change when processing SCI_REPLACETARGET message](https://sourceforge.net/p/scintilla/bugs/2393/)

**Comment by cshnik** [comment]
Fixed.

Regarding the comments from Scintilla's team specified selection change is intended and no proper fix is currently available:
> I am rejecting this as a bug report since the behaviour is intentional.
> It would be possible to offer alternative options but they would have to be defined well. In particular, the behaviour with multiple selections that touch should be specified.

Since Notepad2e already use patched version of Scintilla we decided to implement "dirty" fix which will address this issue and does not brake other functionality (Scintilla's multiple selections are not utilized by N2e).
