### ISSUE TITLE
Eval: comma convertion

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#72]
Add a normalization rule: 
* if the expression is valid 
 * and has only commas, no periods - convert commas to periods
  * if the expression is still valid - use converted
  * if not - revert to original expression

This is needed to eval expressions where comma is decimal part separator (e.g. in Russian). Currently commas are ignored because they're used as thousands separator. Result is always generated using period. With this update these two expressions are the same:
```
12.34+.1 = 12.44
12,34+,1 = 12.44
```
Currently the last evaluates to:1235 because commas are removed.

Commas here should not be converted because a period exists:
```
12.34+,1 = 13.34
```

No convertion because converted expression is incorrect:
```
1,2,3 + 1 -> 1.2.3 + 1
              ^ ^ error
```
So `1,2,3+1=124`.

**Comment by cshnik** [comment]
* if the expression is still valid - use converted

Previously we added some normalization rules and refused from using of "inline" expression evaluation in its implementation because it may heavily slow down total/final evaluation process.

Please clarify the expected result for:
1,2,3 + 1,2 + ,3

Should we test every subexpression <1.2.3>, <1.2>, <.3> separately when comma-convertion is performed? If yes this normalization rule can become a real problem.

**Comment by ProgerXP** [comment]
It's straightforward. 

1. Is expression `1,2,3 + 1,2 + ,3` valid? Yes because commas are currently removed. So if `123 + 12 + 3` is valid then the former is also valid. Condition 1 passed.
2. Does it have commas but no periods? Yes, it's a matter of 1 character scan over the string. Condition 2 passed.
3. Is the converted expression `1.2.3 + 1.2 + .3` valid? No, because `1.2.3` is not valid. Condition 3 not passed, so using the original expression (with commas). Result = 138.

If we had expression `12,3 + 1,2 + ,3` then condition 3 would have passed because `12.3 + 1.2 + .3` is a valid expression so result would be 13.80.
