### ISSUE TITLE
VirusTotal

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#77]
I've noticed one curious thing. Previously I've been checking bin/Release/exe in virustotal.com and they always gave 0 positives. Last build gave 1 positive (https://virustotal.com/en/file/d823d5ff21107518e30092715be67b4bd58ba3b1bedf0dcff054f749b875a144/analysis/1480022374/). Current build gives 2 positives (https://virustotal.com/en/file/85bada197f5f87602c1686f836996b6d0a2953ae8e8dafaefa40ec272b9efa9b/analysis/1480022278/). 

I am sure they are false but what is causing them? Have you changed VS version, OS or something else? Our edits are trivial, I don't see why detection rate is going up.

```
AdWare.ConvertAd.qhs 	
HEUR/QVM10.1.0000.Malware.Gen 
```

**Comment by cshnik** [comment]
There were no recent changes in my working environment.
I made few test builds for foreign projects in the same VS to make sure they will be clean. These were OK. 
The problem looks erratic since the most recent test build gave me 1 positive:
https://virustotal.com/en/file/1adae6c330a5588b1b2d35d228f893727a5436c77d6fcd7c6d31756a3eb5ece3/analysis/1480626162/
> Jiangmin	AdWare.ConvertAd.qhs
